name: "Ensure build success"
on:
  workflow_dispatch:
  pull_request:
  push:

# Only one workflow per branch
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up env file
        run: cp src/types/env.ts.example src/types/env.ts
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
